---
- name: Verify if disk is encrypted
  shell: cryptsetup status {{ disk_name }}_encrypted | grep "is active"
  register: verify_encryption
  failed_when: verify_encryption.rc != 0
  changed_when: false
  notify: Disk encryption succeeded
  become: yes
