---
- name: Get current network interfaces
  command: ip -o link show | awk -F': ' '{print $2}'
  register: interfaces

- name: Fail if the current interface is not found
  fail:
    msg: "No network interface found to rename."
  when: interfaces.stdout.find("enX0") == -1

- name: Rename network interface from enX0 to net0
  command: ip link set enX0 down && ip link set enX0 name net0 && ip link set net0 up
  notify: Restart network

- name: Ensure network persistence
  lineinfile:
    path: /etc/netplan/50-cloud-init.yaml
    regexp: 'enX0'
    line: 'net0'
  notify: Apply netplan
