---
- name: Check current CPU C-state status
  shell: "cat /sys/module/intel_idle/parameters/max_cstate"
  register: cstate_status
  changed_when: false

- name: Check if C-state is enabled
  debug:
    msg: "C-state is currently enabled with value {{ cstate_status.stdout }}"
  when: cstate_status.stdout != "0"

- name: Ensure C-state is disabled persistently via GRUB
  community.general.grub_cmdline:
    name: "intel_idle.max_cstate"
    value: "0"
    state: present
    update_grub: yes
  register: grub_changed

- name: Reboot the system if C-state was changed
  ansible.builtin.reboot:
    msg: "Rebooting to apply persistent C-state changes"
    connect_timeout: 5
    reboot_timeout: 300
  when: grub_changed.changed

- name: Verify C-state is disabled after reboot
    shell: "cat /sys/module/intel_idle/parameters/max_cstate"
    register: new_cstate_status
    changed_when: false

- name: Confirm C-state is disabled
  debug:
    msg: "C-state has been disabled successfully."
  when: new_cstate_status.stdout == "0"
