---
- name: Backup current Netplan configuration
  copy:
    src: /etc/netplan/50-cloud-init.yaml
    dest: /etc/netplan/50-cloud-init.yaml.backup
    remote_src: yes

- name: Update Netplan configuration to rename interface
  become: yes
  template:
    src: templates/netplan_config.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml

- name: Apply Netplan changes
  become: yes
  command: netplan apply
  register: netplan_apply_result
  failed_when: netplan_apply_result.rc != 0

- name: Reboot the system to apply interface changes
  become: yes
  reboot:
    msg: "Rebooting to apply new network interface configuration."
    connect_timeout: 5
    reboot_timeout: 300
    post_reboot_delay: 60
    test_command: "ip link show net0"

- name: Display information about the new interface
  command: ip addr show net0
  register: interface_info

- name: Show new interface information
  debug:
    msg: "{{ interface_info.stdout }}"
