---
- name: Find all non-root partitioned disks
  ansible.builtin.command:
    cmd: "lsblk -dno NAME,TYPE | grep -E 'disk|part'"
    _uses_shell: True
  register: disk_check_output
  changed_when: false
  become: yes

- name: Fail if no non-root partitioned disk is found
  fail:
    msg: "No non-root partitioned disk found on the system."
  when: disk_check_output.stdout == ""
  become: yes
