---
- name: Copy encryption script to the target
  ansible.builtin.copy:
    src: ~/test/ansible_project/roles/role-encrypt-disk/files/encrypt_disk_script.sh
    dest: /tmp/encrypt_disk_script.sh
    mode: '0755'
  become: yes

- name: Encrypting non-root disk
  shell: bash /tmp/encrypt_disk_script.sh {{ disk }}
  args:
    creates: "/dev/mapper/{{ disk }}_encrypted"
  register: encryption_result
  become: yes

- name: Restart the system to apply changes (if required)
  reboot:
    msg: "System is being rebooted to apply disk encryption."
  when: encryption_result is changed
  become: yes

