---
- name: Encrypt the partition with LUKS
  community.crypto.luks_device:
    device: "{{ partition_name }}"
    state: present
    passphrase: "{{ luks_passphrase }}"
    type: luks2
  become: yes
  register: encrypt_result

- name: Ensure encryption succeeded
  ansible.builtin.fail:
    msg: "Encryption failed for {{ partition_name }}."
  when: encrypt_result.failed

- name: Print encryption success message
  ansible.builtin.debug:
    msg: "Partition {{ partition_name }} was successfully encrypted."
