---
- name: Check if the desired interface name already exists
  community.general.nmcli:
    type: connection
  register: all_connections

- name: Fail if desired interface name 'net1' already exists
  fail:
    msg: "The desired interface name 'net1' already exists."
  when: "'net1' in all_connections.connections | map(attribute='name') | list"

- name: Get current active connection
  community.general.nmcli:
    type: connection
    active: yes
  register: active_connection

- name: Set fact for current interface name
  set_fact:
    current_interface: "{{ active_connection.connections[0].device }}"

- name: Rename the network interface from net0 to net1
  community.general.nmcli:
    type: connection
    conn_name: "net0"
    new_name: "net1"
  when: current_interface == "net0"

- name: Apply the changes to the new interface name net1
  community.general.nmcli:
    type: connection
    conn_name: "net1"
    state: present

- name: Verify that the new interface name is active
  community.general.nmcli:
    type: connection
    active: yes
  register: verify_connection
