---
- name: Show detailed interface information
  community.general.nmcli:
    type: device
    state: present
  register: interface_info

- name: Display interface information
  ansible.builtin.debug:
    var: interface_info.devices
