---
- name: Ensure mount point directory exists
  ansible.builtin.file:
    path: /mnt/encrypted
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Mount the encrypted partition
  ansible.builtin.mount:
    path: /mnt/encrypted
    src: /dev/mapper/luks-
    fstype: ext4
    state: mounted
  become: yes

- name: Ensure partition is mounted on reboot
  ansible.builtin.mount:
    path: /mnt/encrypted
    src: /dev/mapper/luks-
    fstype: ext4
    opts: defaults
    state: present
  become: yes
